name: Basic Workflow

on: [push]

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message in bash
        shell: bash
        run: echo "Hello GitHub Actions in bash"

      - name: Print message in sh
        shell: sh
        run: echo "Hello GitHub Actions in sh"