name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Cambia a la versión que uses

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Print message
        run: echo "Hello GitHub Actions"